name: Daily Github-Trending

permissions:
  contents: write

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper and archive migration
        # run the Python script which will move existing date files into year folders,
        # create today's file into year folder, and commit & push changes if any.
        run: |
          python scraper.py
